import React from 'react'
import Footer from './Footer'
import Navbar from './Navbar'
import Head from 'next/head'

const Layout = ({ children }) => {
  const [theme, setTheme] = React.useState('light')

  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-theme={theme}>
        <Navbar theme={theme} setTheme={setTheme} />
        <main className="main-container">{children}</main>

        <Footer />
      </div>
    </>
  )
}

export default Layout
