import Footer from './Footer'
import Navbar from './Navbar'
import Head from 'next/head'

type Props = {
  children?: JSX.Element | JSX.Element[] | string | string[]
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="main-container">{children}</main>
      <Footer />
    </>
  )
}

export default Layout
