import React from 'react'
import Footer from './Footer'
import Navbar from './Navbar'
import Head from 'next/head'

import { IconContext } from 'react-icons'
import { FaMoon, FaSun } from 'react-icons/fa'
import styles from '../../styles/Layout.module.css'

const Layout = ({ children }) => {
  const [theme, setTheme] = React.useState('light')

  const switchTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light'
    setTheme(newTheme)
  }

  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-theme={theme}>
        <Navbar theme={theme} setTheme={setTheme} />
        <main className="main-container">{children}</main>

        <Footer />
      </div>
    </>
  )
}

export default Layout
